import 'package:flutter/material.dart';
import 'package:world_time/services/world_time.dart';

class ChooseLocation extends StatefulWidget {
  @override
  _ChooseLocationState createState() => _ChooseLocationState();
}

class _ChooseLocationState extends State<ChooseLocation> {

   List<WorldTime> locations = [
    WorldTime(url: 'Asia/Kabul', location: 'Afghanistan', flag: 'Afghanistan.png'),
WorldTime(url: 'Europe/Tirane', location: 'Albania', flag: 'Albania.png'),
WorldTime(url: 'Africa/Algiers', location: 'Algeria', flag: 'Algeria.png'),
WorldTime(url: 'Europe/Andorra', location: 'Andorra', flag: 'andorra.png'),
WorldTime(url: 'Africa/Casablanca', location: 'Angola', flag: 'angola.png'),
WorldTime(url: 'America/New_York', location: 'Antigua and Barbuda', flag: 'antigua_barbuda.png'),
WorldTime(url: 'America/Argentina/Buenos_Aires', location: 'Argentina', flag: 'argentina.png'),
WorldTime(url: 'Asia/Yerevan', location: 'Armenia', flag: 'armenia.png'),
WorldTime(url: 'Australia/Brisbane', location: 'Australia', flag: 'australia.png'),
WorldTime(url: 'Europe/Vienna', location: 'Austria', flag: 'austria.png'),
WorldTime(url: 'Asia/Baku', location: 'Azerbaijan', flag: 'azerbaijan.png'),
WorldTime(url: 'America/Nassau', location: 'Bahamas', flag: 'bahamas.png'),
WorldTime(url: 'Asia/Qatar', location: 'Bahrain', flag: 'bahrain.png'),
WorldTime(url: 'Asia/Dhaka', location: 'Bangladesh', flag: 'bangladesh.png'),
WorldTime(url: 'America/Barbados', location: 'Barbados', flag: 'barbados.png'),
WorldTime(url: 'Europe/Minsk', location: 'Belarus', flag: 'belarus.png'),
WorldTime(url: 'Europe/Brussels', location: 'Belgium', flag: 'belgium.png'),
WorldTime(url: 'America/Belize', location: 'Belize', flag: 'belize.png'),
WorldTime(url: 'Africa/Tunis', location: 'Benin', flag: 'benin.png'),
WorldTime(url: 'Asia/Thimphu', location: 'Bhutan', flag: 'bhutan.png'),
WorldTime(url: 'America/La_Paz', location: 'Bolivia', flag: 'bolivia.png'),
WorldTime(url: 'Europe/Amsterdam', location: 'Bosnia and Herzegovina', flag: 'bosnia_herzegovina.png'),
WorldTime(url: 'Africa/Cairo', location: 'Botswana', flag: 'botswana.png'),
WorldTime(url: 'America/Sao_Paulo', location: 'Brazil', flag: 'brazil.png'),
WorldTime(url: 'Asia/Brunei', location: 'Brunei', flag: 'brunei_darussalam.png'),
WorldTime(url: 'Europe/Sofia', location: 'Bulgaria', flag: 'bulgaria.png'),
WorldTime(url: 'Africa/Abidjan', location: 'Burkina Faso', flag: 'burkina_faso.png'),
WorldTime(url: 'Africa/Cairo', location: 'Burundi', flag: 'burundi.png'),
WorldTime(url: 'Atlantic/Cape_Verde', location: 'Cabo Verde', flag: 'cape_verde.png'),
WorldTime(url: 'Asia/Hovd', location: 'Cambodia', flag: 'cambodia.png'),
WorldTime(url: 'Africa/Algiers', location: 'Cameroon', flag: 'cameroon.png'),
WorldTime(url: 'America/Toronto', location: 'Canada', flag: 'canada.png'),
WorldTime(url: 'Africa/Algiers', location: 'Central African Republic (CAR)', flag: 'central_african_republic.png'),
WorldTime(url: 'Africa/Ndjamena', location: 'Chad', flag: 'chad.png'),
WorldTime(url: 'America/Santiago', location: 'Chile', flag: 'chile.png'),
WorldTime(url: 'Asia/Shanghai', location: 'China', flag: 'china.png'),
WorldTime(url: 'America/Bogota', location: 'Colombia', flag: 'colombia.png'),
WorldTime(url: 'Africa/Juba', location: 'Comoros', flag: 'comoros.png'),
WorldTime(url: 'Africa/Lagos', location: 'Congo, Democratic Republic of the', flag: 'congo,_the_democratic_republic_of_the.png'),
WorldTime(url: 'Africa/Lagos', location: 'Congo, Republic of the', flag: 'congo.png'),
WorldTime(url: 'America/Costa_Rica', location: 'Costa Rica', flag: 'costa_rica.png'),
WorldTime(url: 'Africa/Abidjan', location: 'Cote dIvoire', flag: 'cote_d.png'),
WorldTime(url: 'Africa/Khartoum', location: 'Croatia', flag: 'croatia.png'),
WorldTime(url: 'America/Havana', location: 'Cuba', flag: 'cuba.png'),
WorldTime(url: 'Asia/Nicosia', location: 'Cyprus', flag: 'cyprus.png'),
WorldTime(url: 'Europe/Prague', location: 'Czechia', flag: 'czech_republic.png'),
WorldTime(url: 'Europe/Copenhagen', location: 'Denmark', flag: 'denmark.png'),
WorldTime(url: 'Africa/Nairobi', location: 'Djibouti', flag: 'djibouti.png'),
WorldTime(url: 'America/Kentucky/Louisvill', location: 'Dominica', flag: 'dominica.png'),
WorldTime(url: 'America/Kentucky/Louisvill', location: 'Dominican Republic', flag: 'dominican_republic.png'),
WorldTime(url: 'America/Lima', location: 'Ecuador', flag: 'ecuador.png'),
WorldTime(url: 'Africa/Cairo', location: 'Egypt', flag: 'egypt.png'),
WorldTime(url: 'America/El_Salvador', location: 'El Salvador', flag: 'el_salvador.png'),
WorldTime(url: 'Africa/Lagos', location: 'Equatorial Guinea', flag: 'equatorial_guinea.png'),
WorldTime(url: 'Africa/Juba', location: 'Eritrea', flag: 'eritrea.png'),
WorldTime(url: 'Europe/Tallinn', location: 'Estonia', flag: 'estonia.png'),
WorldTime(url: 'Africa/Maputo', location: 'Eswatini (formerly Swaziland)', flag: 'swaziland.png'),
WorldTime(url: 'Africa/Nairobi', location: 'Ethiopia', flag: 'ethiopia.png'),
WorldTime(url: 'Pacific/Fiji', location: 'Fiji', flag: 'fiji.png'),
WorldTime(url: 'Europe/Helsinki', location: 'Finland', flag: 'finland.png'),
WorldTime(url: 'Europe/Paris', location: 'France', flag: 'france.png'),
WorldTime(url: 'Africa/Algiers', location: 'Gabon', flag: 'gabon.png'),
WorldTime(url: 'Africa/Bissau', location: 'Gambia', flag: 'gambia.png'),
WorldTime(url: 'Asia/Tbilisi', location: 'Georgia', flag: 'georgia.png'),
WorldTime(url: 'Europe/Berlin', location: 'Germany', flag: 'germany.png'),
WorldTime(url: 'Africa/Accra', location: 'Ghana', flag: 'ghana.png'),
WorldTime(url: 'Europe/Athens', location: 'Greece', flag: 'greece.png'),
WorldTime(url: 'Asia/Tbilisi', location: 'Grenada', flag: 'grenada.png'),
WorldTime(url: 'America/Guatemala', location: 'Guatemala', flag: 'guatemala.png'),
WorldTime(url: 'Africa/Bissau', location: 'Guinea-Bissau', flag: 'guinea_bissau.png'),
WorldTime(url: 'America/Guyana', location: 'Guyana', flag: 'guyana.png'),
WorldTime(url: 'America/Port-au-Prince', location: 'Haiti', flag: 'haiti.png'),
WorldTime(url: 'America/Tegucigalpa', location: 'Honduras', flag: 'honduras.png'),
WorldTime(url: 'Europe/Budapest', location: 'Hungary', flag: 'hungary.png'),
WorldTime(url: 'Atlantic/Reykjavik', location: 'Iceland', flag: 'iceland.png'),
WorldTime(url: 'Asia/Kolkata', location: 'India', flag: 'india.png'),
WorldTime(url: 'Asia/Jakarta', location: 'Indonesia', flag: 'indonesia.png'),
WorldTime(url: 'Asia/Tehran', location: 'Iran', flag: 'iran.png'),
WorldTime(url: 'Asia/Qatar', location: 'Iraq', flag: 'iraq.png'),
WorldTime(url: 'Europe/Dublin', location: 'Ireland', flag: 'ireland.png'),
WorldTime(url: 'Asia/Jerusalem', location: 'Israel', flag: 'israel.png'),
WorldTime(url: 'Europe/Rome', location: 'Italy', flag: 'italy.png'),
WorldTime(url: 'America/Jamaica', location: 'Jamaica', flag: 'jamaica.png'),
WorldTime(url: 'Asia/Tokyo', location: 'Japan', flag: 'japan.png'),
WorldTime(url: 'Asia/Jerusalem', location: 'Jordan', flag: 'jordan.png'),
WorldTime(url: 'Asia/Almaty', location: 'Kazakhstan', flag: 'kazakhstan.png'),
WorldTime(url: 'Africa/Nairobi', location: 'Kenya', flag: 'kenya.png'),
WorldTime(url: 'Pacific/Tarawa', location: 'Kiribati', flag: 'kiribati.png'),
WorldTime(url: 'Europe/Kaliningrad', location: 'Kosovo', flag: 'kosovo.png'),
WorldTime(url: 'Asia/Gaza', location: 'Kuwait', flag: 'kuwait.png'),
WorldTime(url: 'Asia/Bishkek', location: 'Kyrgyzstan', flag: 'kyrgyzstan.png'),
WorldTime(url: 'Asia/Krasnoyarsk', location: 'Laos', flag: 'lao_people.png'),
WorldTime(url: 'Europe/Riga', location: 'Latvia', flag: 'latvia.png'),
WorldTime(url: 'Asia/Beirut', location: 'Lebanon', flag: 'lebanon.png'),
WorldTime(url: 'Africa/Tripoli', location: 'Lesotho', flag: 'lesotho.png'),
WorldTime(url: 'Africa/Monrovia', location: 'Liberia', flag: 'liberia.png'),
WorldTime(url: 'Africa/Tripoli', location: 'Libya', flag: 'libyan_arab_jamahiriya.png'),
WorldTime(url: 'Europe/Malta', location: 'Liechtenstein', flag: 'liechtenstein.png'),
WorldTime(url: 'Europe/Vilnius', location: 'Lithuania', flag: 'lithuania.png'),
WorldTime(url: 'Europe/Luxembourg', location: 'Luxembourg', flag: 'luxembourg.png'),
WorldTime(url: 'Africa/Nairobi', location: 'Madagascar', flag: 'madagascar.png'),
WorldTime(url: 'Africa/Windhoek', location: 'Malawi', flag: 'malawi.png'),
WorldTime(url: 'Asia/Kuala_Lumpur', location: 'Malaysia', flag: 'malaysia.png'),
WorldTime(url: 'Indian/Maldives', location: 'Maldives', flag: 'maldives.png'),
WorldTime(url: 'Africa/Accra', location: 'Mali', flag: 'mali.png'),
WorldTime(url: 'Europe/Malta', location: 'Malta', flag: 'malta.png'),
WorldTime(url: 'Pacific/Majuro', location: 'Marshall Islands', flag: 'marshall_islands.png'),
WorldTime(url: 'Africa/Accra', location: 'Mauritania', flag: 'mauritania.png'),
WorldTime(url: 'Indian/Mauritius', location: 'Mauritius', flag: 'mauritius.png'),
WorldTime(url: 'America/Mexico_City', location: 'Mexico', flag: 'mexico.png'),
WorldTime(url: 'Pacific/Pohnpei', location: 'Micronesia', flag: 'micronesia.png'),
WorldTime(url: 'Europe/Chisinau', location: 'Moldova', flag: 'moldova.png'),
WorldTime(url: 'Europe/Monaco', location: 'Monaco', flag: 'monaco.png'),
WorldTime(url: 'Asia/Ulaanbaatar', location: 'Mongolia', flag: 'mongolia.png'),
WorldTime(url: 'Europe/Madrid', location: 'Montenegro', flag: 'me.png'),
WorldTime(url: 'Africa/Casablanca', location: 'Morocco', flag: 'morocco.png'),
WorldTime(url: 'Africa/Maputo', location: 'Mozambique', flag: 'mozambique.png'),
WorldTime(url: 'Asia/Yangon', location: 'Myanmar (formerly Burma)', flag: 'myanmar.png'),
WorldTime(url: 'Africa/Windhoek', location: 'Namibia', flag: 'namibia.png'),
WorldTime(url: 'Pacific/Nauru', location: 'Nauru', flag: 'nauru.png'),
WorldTime(url: 'Asia/Kathmandu', location: 'Nepal', flag: 'nepal.png'),
WorldTime(url: 'Europe/Amsterdam', location: 'Netherlands', flag: 'netherlands.png'),
WorldTime(url: 'Pacific/Auckland', location: 'New Zealand', flag: 'new_zealand.png'),
WorldTime(url: 'America/Managua', location: 'Nicaragua', flag: 'nicaragua.png'),
WorldTime(url: 'Africa/Algiers', location: 'Niger', flag: 'niger.png'),
WorldTime(url: 'Africa/Lagos', location: 'Nigeria', flag: 'nigeria.png'),
WorldTime(url: 'Asia/Pontianak', location: 'North Korea', flag: 'korea.png'),
WorldTime(url: 'Europe/Madrid', location: 'North Macedonia (formerly Macedonia)', flag: 'macedonia.png'),
WorldTime(url: 'Europe/Oslo', location: 'Norway', flag: 'norway.png'),
WorldTime(url: 'Asia/Dubai', location: 'Oman', flag: 'oman.png'),
WorldTime(url: 'Asia/Karachi', location: 'Pakistan', flag: 'pakistan.png'),
WorldTime(url: 'Pacific/Palau', location: 'Palau', flag: 'palau.png'),
WorldTime(url: 'Asia/Gaza', location: 'Palestine', flag: 'palestine.png'),
WorldTime(url: 'America/Panama', location: 'Panama', flag: 'panama.png'),
WorldTime(url: 'Pacific/Port_Moresby', location: 'Papua New Guinea', flag: 'papua_new_guinea.png'),
WorldTime(url: 'America/Asuncion', location: 'Paraguay', flag: 'paraguay.png'),
WorldTime(url: 'America/Lima', location: 'Peru', flag: 'peru.png'),
WorldTime(url: 'Asia/Manila', location: 'Philippines', flag: 'philippines.png'),
WorldTime(url: 'Europe/Warsaw', location: 'Poland', flag: 'poland.png'),
WorldTime(url: 'Europe/Lisbon', location: 'Portugal', flag: 'portugal.png'),
WorldTime(url: 'Asia/Qatar', location: 'Qatar', flag: 'qatar.png'),
WorldTime(url: 'Europe/Bucharest', location: 'Romania', flag: 'romania.png'),
WorldTime(url: 'Europe/Moscow', location: 'Russia', flag: 'russia.png'),
WorldTime(url: 'Africa/Tripoli', location: 'Rwanda', flag: 'rwanda.png'),
WorldTime(url: 'America/Caracas', location: 'Saint Kitts and Nevis', flag: 'saint_ktts__nevis.png'),
WorldTime(url: 'America/New_York', location: 'Saint Lucia', flag: 'saint_lucia.png'),
WorldTime(url: 'America/Caracas', location: 'Saint Vincent and the Grenadines', flag: 'saint_vincent_thegrenadines.png'),
WorldTime(url: 'Pacific/Apia', location: 'Samoa', flag: 'samoa.png'),
WorldTime(url: 'Europe/Copenhagen', location: 'San Marino', flag: 'san_marino.png'),
WorldTime(url: 'Africa/Sao_Tome', location: 'Sao Tome and Principe', flag: 'sao_tome_principe.png'),
WorldTime(url: 'Asia/Riyadh', location: 'Saudi Arabia', flag: 'saudi_arabia.png'),
WorldTime(url: 'Africa/Bissau', location: 'Senegal', flag: 'senegal.png'),
WorldTime(url: 'Europe/Belgrade', location: 'Serbia', flag: 'serbia.png'),
WorldTime(url: 'Europe/Samara', location: 'Seychelles', flag: 'seychelles.png'),
WorldTime(url: 'Africa/Monrovia', location: 'Sierra Leone', flag: 'sierra_leone.png'),
WorldTime(url: 'Asia/Singapore', location: 'Singapore', flag: 'singapore.png'),
WorldTime(url: 'Europe/Malta', location: 'Slovakia', flag: 'slovakia.png'),
WorldTime(url: 'Europe/Kaliningrad', location: 'Slovenia', flag: 'slovenia.png'),
WorldTime(url: 'Pacific/Guadalcanal', location: 'Solomon Islands', flag: 'solomon_islands.png'),
WorldTime(url: 'Africa/Juba', location: 'Somalia', flag: 'somalia.png'),
WorldTime(url: 'Africa/Johannesburg', location: 'South Africa', flag: 'south_africa.png'),
WorldTime(url: 'Asia/Seoul', location: 'South Korea', flag: 'sk.png'),
WorldTime(url: 'Africa/Juba', location: 'South Sudan', flag: 'ss.png'),
WorldTime(url: 'Europe/Madrid', location: 'Spain', flag: 'spain.png'),
WorldTime(url: 'Asia/Colombo', location: 'Sri Lanka', flag: 'srilanka.png'),
WorldTime(url: 'Africa/Khartoum', location: 'Sudan', flag: 'sudan.png'),
WorldTime(url: 'America/Paramaribo', location: 'Suriname', flag: 'suriname.png'),
WorldTime(url: 'Europe/Stockholm', location: 'Sweden', flag: 'sweden.png'),
WorldTime(url: 'Europe/Zurich', location: 'Switzerland', flag: 'switzerland.png'),
WorldTime(url: 'Asia/Damascus', location: 'Syria', flag: 'syrian_arab_republic.png'),
WorldTime(url: 'Asia/Taipei', location: 'Taiwan', flag: 'taiwan.png'),
WorldTime(url: 'Asia/Dushanbe', location: 'Tajikistan', flag: 'tajikistan.png'),
WorldTime(url: 'Africa/Nairobi', location: 'Tanzania', flag: 'tanzania.png'),
WorldTime(url: 'Asia/Bangkok', location: 'Thailand', flag: 'thailand.png'),
WorldTime(url: 'Asia/Dili', location: 'Timor-Leste', flag: 'limor-leste.png'),
WorldTime(url: 'Africa/Monrovia ', location: 'Togo', flag: 'togo.png'),
WorldTime(url: 'Pacific/Tongatapu', location: 'Tonga', flag: 'tonga.png'),
WorldTime(url: 'America/Port_of_Spain', location: 'Trinidad and Tobago', flag: 'trinidad_tobago.png'),
WorldTime(url: 'Africa/Tunis', location: 'Tunisia', flag: 'tunisia.png'),
WorldTime(url: 'Europe/Istanbul', location: 'Turkey', flag: 'turkey.png'),
WorldTime(url: 'Asia/Aqtau', location: 'Turkmenistan', flag: 'turkmenistan.png'),
WorldTime(url: 'Pacific/Funafuti', location: 'Tuvalu', flag: 'tuvalu.png'),
WorldTime(url: 'Africa/Nairobi', location: 'Uganda', flag: 'uganda.png'),
WorldTime(url: 'Europe/Kiev', location: 'Ukraine', flag: 'ukraine.png'),
WorldTime(url: 'Asia/Dubai', location: 'UAE', flag: 'UAE.png'),
WorldTime(url: 'Europe/London', location: 'United Kingdom (UK)', flag: 'uk.png'),
WorldTime(url: 'America/New_York', location: 'USA', flag: 'us.png'),
WorldTime(url: 'America/Montevideo', location: 'Uruguay', flag: 'uruguay.png'),
WorldTime(url: 'Asia/Tashkent', location: 'Uzbekistan', flag: 'uzbekistan.png'),
WorldTime(url: 'Pacific/Bougainville', location: 'Vanuatu', flag: 'vanuatu.png'),
WorldTime(url: 'Europe/Rome', location: 'Vatican City (Holy See)', flag: 'holy_see.png'),
WorldTime(url: 'America/Caracas', location: 'Venezuela', flag: 'venezuela.png'),
WorldTime(url: 'Asia/Ho_Chi_Minh', location: 'Vietnam', flag: 'vietnam.png'),
WorldTime(url: 'Asia/Gaza', location: 'Yemen', flag: 'yemen.png'),
WorldTime(url: 'Africa/Cairo', location: 'Zambia', flag: 'zambia.png'),
WorldTime(url: 'Africa/Cairo', location: 'Zimbabwe', flag: 'zimbabwe.png'),



  ];
  
  void updateTime(index) async{
    WorldTime instance = locations[index];
    await instance.getTime();
    //navigate to home screen
    Navigator.pop(context,{
      'location': instance.location,
      'flag': instance.flag,
      'time': instance.time,
      'isDaytime': instance.isDaytime,
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.grey[200],
      appBar: AppBar(
        backgroundColor: Colors.blue[900],
        title: Text('Choose a location'),
        centerTitle: true,
        elevation: 0,
      ),
      body: ListView.builder(
        itemCount : locations.length,
        itemBuilder : (context,index){
          return Padding(
            padding: const EdgeInsets.symmetric(vertical: 1.0, horizontal: 4.0),
            child: Card(
              child: ListTile(
                onTap: () {
                  updateTime(index);
                },
                title: Text(locations[index].location),
                leading: CircleAvatar(
                  backgroundImage: AssetImage('assets/${locations[index].flag}'),
                ),
              ),
            ),
          );
        }
      ),
      
    );
  }
}